### ISSUE TITLE
Team 가입 신청

### ISSUE THREAD

**Issue by juni37** [Team-Union/others#1]
Team Union에 오신것을 환영합니다. 
특정 레포지토리에 접근하시려면, Team에 가입하셔야 접근 권한이 부여됩니다.
아래 팀을 확인하시고, 레포지토리에 접근해주십시오.

- Team Bot : 봇들을 개발하는 팀이며, UniT/Forum Bot 등의 레포지토리가 있습니다.
- Team Indent : 키리스트님이 소유하시는 팀이며, 개발자들을 위한 페이스북과 같은 소셜 서비스입니다. indent 레포지토리가 있습니다.
이 팀은 키리스트님이 권한을 부여할 수 있습니다. 
- Team Website : 웹사이트를 제작하는 팀입니다. Blog / UniT Web / Website 등의 레포지토리가 있습니다.
- Team Sirius : 팀 시리우스입니다. 호스팅 프로젝트를 진행하고 있으며, 현재 레포지토리는 없습니다.
관련 가입 문의는 @Mireu-Labcon 에게 부탁드립니다!
- Team Event : 이벤트 관련 모든것을 제작하는 팀입니다. GG Media 소속 팀입니다. 현재 TEXTMOTION 및 Event-Stuff 레포지토리가 있습니다.
이 팀은 @G10010 님이 권한을 부여할 수 있습니다.
- Team Endint : 웹 및 봇을 개발하는 팀이며, Team End 부서 팀입니다. 현재 레포지토리가 없습니다.
이 팀은 @Tim232 님이 권한을 부여할 수 있습니다.
- Team UniT : UniT에 관련된 모든것을 관리하는 팀입니다. UniT / UniT-Web 등의 레포지토리가 있습니다.

위에 나오지 않은 레포지토리들은 Public으로 변경할 예정입니다. Team 을 개설하고 싶으신 분들께서는 Team Union으로 DM을 보내주시기 바랍니다. (Public에서 Private 변환 가능)

팀 신청 양식은 다음과 같습니다.
- 신청하는 팀 이름 : 
- 디스코드 닉네임 : 
감사합니다.

**Comment by jwkim101201** [comment]
디슨스는 어딘가여

**Comment by juni37** [comment]
https://github.com/Team-Union/others/issues/1#issuecomment-781832778
현재 Disns 레포지토리는 특정 팀에 Assign 되지 않아 Public으로, 자유롭게 작업하실 수 있습니다.

**Comment by Mireu-Labcon** [comment]
신청하는 팀 이름 : Team sirius
디스코드 닉네임 : mireu/미르

**Comment by Mireu-Labcon** [comment]
아 이미 있구나

**Comment by kellsthepenguin** [comment]
신청하는 팀 이름: team bot
디스코드 닉네임: 김껠쓰#5150

**Comment by chul0721** [comment]
네 그리고 이 해당 깃허브에 가입하려면 저한테 문의하시면 됩니당 쿠쿠루

**Comment by chul0721** [comment]
Team indent는 제가 소유중입니다. 확인해주세요
@juni37

**Comment by Tim232** [comment]
같이소유하는건데

2021년 2월 19일 (금) 오후 2:48, int <notifications@github.com>님이 작성:

**Comment by Tim232** [comment]
@chul0721 같이 소유하는건데

**Comment by Tim232** [comment]
endint가 엔드랑 인트랑 합친거에여

**Comment by chul0721** [comment]
아니 endint는 같이 소유고 indent는 키리님이 아닌 제꺼;;

**Comment by juni37** [comment]
@Team-Union/team-indent 관련 말씀이시라면 키리스트님께 권한을 부여하여야 하는데 키리스트님께서 현재 저희 깃허브에 초대가 되어 있지

**Comment by Tim232** [comment]
indent 그냥 endint 프젝중 하나에요

**Comment by chul0721** [comment]
? 모르면 가만히계세요
프젝중하나아닙니다만

**Comment by chul0721** [comment]
+ organization 분리되어있어서 곧 옮길예정

**Comment by Tim232** [comment]
디스코드 보면 project-intent라고 써잇던데

**Comment by Tim232** [comment]
> + organization 분리되어있어서 곧 옮길예정

end랑 int 말하는건가

**Comment by chul0721** [comment]
그건 유니온이랑 시리우스에도 있음
그냥 존재하는거

**Comment by chul0721** [comment]
아니 인덴트가 분리됨

**Comment by Tim232** [comment]
아

**Comment by Tim232** [comment]
나도 그 인덴트 하는거지?

**Comment by Tim232** [comment]
근데 왜 이름이 인덴트
